### ISSUE TITLE
No reference of doxygen documentation on readthedocs

### ISSUE THREAD

**Issue by carme-hp** [opendihu/opendihu#31]
This is a follow up from #30.

**Comment by Conni2461** [comment]
what we could do is host the doxygen configuration through github pages, and then link them. i think it would be useful to have the full code reference hosted for users of this framework

**Comment by carme-hp** [comment]
Ideally i would like to have all the documentation hosted in the same place. 

> what we could do is host the doxygen configuration through github pages, and then link them.

I see this as a good intermediate solution, I'll think about it.
