### ISSUE TITLE
Transfer the original opendihu repo to this new home

### ISSUE THREAD

**Issue by maierbn** [opendihu/opendihu#5]
OpenDiHu moves from [the repo under my account](https://github.com/maierbn/opendihu) to here.

- [x] Add note and links to new repo in readme and docs of old repo
- [x] Archive old docs - I moved the last static build to Github Pages of the old repo ([link](https://maierbn.github.io/opendihu/))
- [x] Link https://opendihu.readthedocs.io/en/latest/ to the new repo. 
  - I tried it out and I could simply update the URL in readthedocs. Since the configuration is identical to before, the build still works.
  - But it would be better if @carme-hp or the "opendihu" Orga itself sets it up with Readthedocs. I can delete my old project to make the name free. We should coordinate to reduce downtime.
- [x] Add links and a note on the new readthedocs page
- [x] I will archive the old repo. The old issues are already closed. It's not possible to transfer the issues so the issue authors can reopen them here, and copy all the text and images etc.

**Comment by carme-hp** [comment]
Thanks for setting up the checklist. I will have tome to do the read the docs repo tomorrow 21.01 between 12pm and  5pm. Would that work?

**Comment by maierbn** [comment]
I'm a bit busy tomorrow. I think I'll remove the readthedocs project now then you can do it tomorrow. I think a downtime of one day on a weekend is okay.

Are you fine with the notes and links on the old repo?

**Comment by maierbn** [comment]
ok done

**Comment by carme-hp** [comment]
Note added in new repo (see #8)
